services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_main
    ports:
      - 5450:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

